service: aqts-capture-ecosystem-switch

provider:
  name: aws
  region: ${opt:region, 'us-west-2'}
  stage: ${opt:stage, 'TEST'}
  runtime: python3.8
  memorySize: 128
  timeout: 90
  logRetentionInDays: 90
  deploymentBucket:
    name: ${opt:bucket, iow-cloud-applications}
  stackTags:
    "wma:applicationId": "Aquarius TS Capture Ecosystem Switch"
    "wma:contact": "Kenneth Kehl kkehl@contractor.usgs.gov"
    "wma:environment": ${self:provider.stage}
    "wma:taggingVersion": 0.0.1
    "wma:costCenter": TBD
    "wma:organization": IOW
    "displayName": "Eco-switch"
    "wma:role": etl
    "wma:system": NWIS
    "wma:subSystem": NWISWeb-Capture
    commitIdentifier: ${git:sha1}

custom:
  # https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/ScheduledEvents.html#CronExpressions
  # The test database starts at 7 am central and stops at 6 pm central time, Monday through Friday.
  # The qa database stops at 6 pm central on Fridays
  # The production database never stops or starts according to a schedule, the lambdas exist only for manual use.
  environments:
    DEV: dev
    TEST: test
    QA: qa
    PROD: prod
  startObservationSchedules:
    TEST: cron(0 12 ? * MON-FRI *)
    QA: cron(0 12 ? * MON *)
    PROD: cron(0 12 ? * MON *)
  stopObservationSchedules:
    TEST: cron(0 23 ? * MON-FRI *)
    QA: cron(0 23 ? * FRI *)
    PROD: cron(0 23 ? * FRI *)
  startCaptureSchedules:
    TEST: cron(0 12 ? * MON-FRI *)
    QA: cron(0 12 ? * MON *)
    PROD: cron(0 12 ? * MON *)
  stopCaptureSchedules:
    TEST: cron(0 23 ? * MON-FRI *)
    QA: cron(0 23 ? * FRI *)
    PROD: cron(0 23 ? * FRI *)
  # No scheduling enabled for prod.  For qa, only Friday stops are scheduled.  For test, both stop and
  # starts are scheduled.
  startCaptureDbScheduleEnabled:
    TEST: true
    QA: false
    PROD: false
  startObservationDbScheduleEnabled:
    TEST: true
    QA: false
    PROD: false
  stopCaptureDbScheduleEnabled:
    TEST: true
    QA: false
    PROD: false
  stopObservationDbScheduleEnabled:
    TEST: true
    QA: true
    PROD: false

  exportGitVariables: false
  vpc:
    securityGroupIds: ${ssm:/iow/retriever-capture/${self:provider.stage}/securityGroupIds~split}
    subnetIds: ${ssm:/iow/aws/vpc/${self:provider.stage}/subnetIds~split}
  observationsDb:
    connectInfo: ${ssm:/aws/reference/secretsmanager/WQP-EXTERNAL-${self:provider.stage}~true}

functions:
  # TODO REMOVE
  CopyS3:
    handler: src.handler.copy_s3
    role: arn:aws:iam::#{AWS::AccountId}:role/csr-Lambda-Role
    environment:
      AWS_DEPLOYMENT_REGION: ${self:provider.region}
      LOG_LEVEL: INFO
      STAGE: ${self:provider.stage}
    vpc: ${self:custom.vpc}

  StartObservationsDb:
    handler: src.handler.start_observations_db
    role: arn:aws:iam::#{AWS::AccountId}:role/csr-Lambda-Role
    environment:
      AWS_DEPLOYMENT_REGION: ${self:provider.region}
      STAGE: ${self:provider.stage}
    events:
      - schedule:
          rate: ${self:custom.startObservationSchedules.${self:provider.stage}}
          enabled: ${self:custom.startObservationDbScheduleEnabled.${self:provider.stage}}
    vpc: ${self:custom.vpc}

  StopObservationsDb:
    handler: src.handler.stop_observations_db
    role: arn:aws:iam::#{AWS::AccountId}:role/csr-Lambda-Role
    environment:
      DB_HOST: ${self:custom.observationsDb.connectInfo.DATABASE_ADDRESS}
      DB_USER: ${self:custom.observationsDb.connectInfo.WQP_READ_ONLY_USERNAME}
      DB_NAME: ${self:custom.observationsDb.connectInfo.DATABASE_NAME}
      DB_PASSWORD: ${self:custom.observationsDb.connectInfo.WQP_READ_ONLY_PASSWORD}
      AWS_DEPLOYMENT_REGION: ${self:provider.region}
      STAGE: ${self:provider.stage}
    events:
      - schedule:
          rate: ${self:custom.stopObservationSchedules.${self:provider.stage}}
          enabled: ${self:custom.stopObservationDbScheduleEnabled.${self:provider.stage}}
    vpc: ${self:custom.vpc}

  StartCaptureDb:
    handler: src.handler.start_capture_db
    role: arn:aws:iam::#{AWS::AccountId}:role/csr-Lambda-Role
    environment:
      AWS_DEPLOYMENT_REGION: ${self:provider.region}
      STAGE: ${self:provider.stage}
    events:
      - schedule:
          rate: ${self:custom.startCaptureSchedules.${self:provider.stage}}
          enabled: ${self:custom.startCaptureDbScheduleEnabled.${self:provider.stage}}
    vpc: ${self:custom.vpc}

  StopCaptureDb:
    handler: src.handler.stop_capture_db
    role: arn:aws:iam::#{AWS::AccountId}:role/csr-Lambda-Role
    environment:
      AWS_DEPLOYMENT_REGION: ${self:provider.region}
      STAGE: ${self:provider.stage}
    events:
      - schedule:
          rate: ${self:custom.stopCaptureSchedules.${self:provider.stage}}
          enabled: ${self:custom.stopCaptureDbScheduleEnabled.${self:provider.stage}}
    vpc: ${self:custom.vpc}

  ControlDbUtilization:
    handler: src.handler.control_db_utilization
    role: arn:aws:iam::#{AWS::AccountId}:role/csr-Lambda-Role
    environment:
      AWS_DEPLOYMENT_REGION: ${self:provider.region}
      LOG_LEVEL: INFO
      STAGE: ${self:provider.stage}
    events:
      - cloudwatchEvent:
          event:
            source:
              - 'aws.cloudwatch'
            detail:
              alarmName: ["aqts-capture-error-handler-${self:provider.stage}-error-alarm"]
    vpc: ${self:custom.vpc}

  disableTriggerBeforeResize:
    handler: src.db_resize_handler.disable_trigger_before_resize
    role: arn:aws:iam::#{AWS::AccountId}:role/csr-Lambda-Role
    environment:
      AWS_DEPLOYMENT_REGION: ${self:provider.region}
      LOG_LEVEL: INFO
      STAGE: ${self:provider.stage}
    vpc: ${self:custom.vpc}

  enableTriggerAfterResize:
    handler: src.db_resize_handler.enable_trigger_after_resize
    role: arn:aws:iam::#{AWS::AccountId}:role/csr-Lambda-Role
    environment:
      AWS_DEPLOYMENT_REGION: ${self:provider.region}
      LOG_LEVEL: INFO
      STAGE: ${self:provider.stage}
    vpc: ${self:custom.vpc}

  # The SHRINK_EVAL_TIME_IN_SECONDS should match the schedule
  # The SHRINK_THRESHOLD is the percentage of cpu utilization
  shrinkDb:
    handler: src.db_resize_handler.shrink_db
    role: arn:aws:iam::#{AWS::AccountId}:role/csr-Lambda-Role
    environment:
      AWS_DEPLOYMENT_REGION: ${self:provider.region}
      LOG_LEVEL: INFO
      SHRINK_THRESHOLD: "10"
      SHRINK_EVAL_TIME_IN_SECONDS: "3600"
      STAGE: ${self:provider.stage}
    events:
      - schedule:
          rate: rate(1 hour)
    vpc: ${self:custom.vpc}

  growDb:
    handler: src.db_resize_handler.grow_db
    role: arn:aws:iam::#{AWS::AccountId}:role/csr-Lambda-Role
    environment:
      AWS_DEPLOYMENT_REGION: ${self:provider.region}
      LOG_LEVEL: INFO
      STAGE: ${self:provider.stage}

  executeShrinkMachine:
    handler: src.db_resize_handler.execute_shrink_machine
    role: arn:aws:iam::#{AWS::AccountId}:role/csr-Lambda-Role
    environment:
      AWS_DEPLOYMENT_REGION: ${self:provider.region}
      SHRINK_STATE_MACHINE_ARN: arn:aws:states:${self:provider.region}:#{AWS::AccountId}:stateMachine:aqts-ecosystem-switch-shrink-db-${self:provider.stage}
      LOG_LEVEL: INFO
      STAGE: ${self:provider.stage}
    events:
      - schedule:
          rate: rate(15 minutes)
          enabled: true
    vpc: ${self:custom.vpc}

  executeGrowMachine:
    handler: src.db_resize_handler.execute_grow_machine
    role: arn:aws:iam::#{AWS::AccountId}:role/csr-Lambda-Role
    environment:
      AWS_DEPLOYMENT_REGION: ${self:provider.region}
      SHRINK_STATE_MACHINE_ARN: arn:aws:states:${self:provider.region}:#{AWS::AccountId}:stateMachine:aqts-ecosystem-switch-grow-db-${self:provider.stage}
      LOG_LEVEL: INFO
      STAGE: ${self:provider.stage}
    events:
      - cloudwatchEvent:
          event:
            source:
              - 'aws.cloudwatch'
            detail:
              alarmName: [ "aqts-capture-ecosystem-switch-${self:provider.stage}-grow-db-alarm" ]
    vpc: ${self:custom.vpc}

  restoreDbCluster:
    handler: src.handler.restore_db_cluster
    role: arn:aws:iam::#{AWS::AccountId}:role/csr-Lambda-Role
    environment:
      AWS_DEPLOYMENT_REGION: ${self:provider.region}
      STAGE: ${self:provider.stage}
      LOG_LEVEL: INFO
    vpc: ${self:custom.vpc}

  modifyPostgresPassword:
    handler: src.handler.modify_postgres_password
    role: arn:aws:iam::#{AWS::AccountId}:role/csr-Lambda-Role
    environment:
      AWS_DEPLOYMENT_REGION: ${self:provider.region}
      STAGE: ${self:provider.stage}
      LOG_LEVEL: INFO
    vpc: ${self:custom.vpc}

  createDbInstance:
    handler: src.handler.create_db_instance
    role: arn:aws:iam::#{AWS::AccountId}:role/csr-Lambda-Role
    environment:
      AWS_DEPLOYMENT_REGION: ${self:provider.region}
      STAGE: ${self:provider.stage}
      LOG_LEVEL: INFO
    vpc: ${self:custom.vpc}

  modifySchemaOwnerPassword:
    handler: src.handler.modify_schema_owner_password
    role: arn:aws:iam::#{AWS::AccountId}:role/csr-Lambda-Role
    environment:
      AWS_DEPLOYMENT_REGION: ${self:provider.region}
      STAGE: ${self:provider.stage}
      LOG_LEVEL: INFO
    vpc: ${self:custom.vpc}

  deleteCaptureDb:
    handler: src.handler.delete_capture_db
    role: arn:aws:iam::#{AWS::AccountId}:role/csr-Lambda-Role
    environment:
      AWS_DEPLOYMENT_REGION: ${self:provider.region}
      STAGE: ${self:provider.stage}
      LOG_LEVEL: INFO
    vpc: ${self:custom.vpc}

stepFunctions:
  stateMachines:
    aqtsCreateCaptureDb:
      loggingConfig:
        level: ALL
        includeExecutionData: true
        destinations:
          - arn:aws:logs:${self:provider.region}:#{AWS::AccountId}:log-group:step-functions-test:*
      role: arn:aws:iam::#{AWS::AccountId}:role/step-functions-service-access
      name: aqts-capture-ecosystem-switch-create-db-${self:provider.stage}
      definition:
        Comment: "AQTS CreateCaptureDb"
        StartAt: RestoreDbCluster
        States:
          RestoreDbCluster:
            Type: Task
            Resource:
              Fn::GetAtt: [restoreDbCluster, Arn]
            Next: ModifyPostgresPassword
          ModifyPostgresPassword:
            Type: Task
            Resource:
              Fn::GetAtt: [modifyPostgresPassword, Arn]
            Retry:
              - ErrorEquals:
                  - States.ALL
                IntervalSeconds: 600
                MaxAttempts: 12
                BackoffRate: 1
            Next: CreateDbInstance
          CreateDbInstance:
            Type: Task
            Resource:
              Fn::GetAtt: [createDbInstance, Arn]
            Retry:
              - ErrorEquals:
                  - States.ALL
                IntervalSeconds: 600
                MaxAttempts: 12
                BackoffRate: 1
            Next: ModifySchemaOwnerPassword
          ModifySchemaOwnerPassword:
            Type: Task
            Resource:
              Fn::GetAtt: [ modifySchemaOwnerPassword, Arn ]
            Retry:
              - ErrorEquals:
                  - States.ALL
                IntervalSeconds: 60
                MaxAttempts: 30
                BackoffRate: 1
            End: true

    aqtsShrinkDb:
      loggingConfig:
        level: ALL
        includeExecutionData: true
        destinations:
          - arn:aws:logs:${self:provider.region}:#{AWS::AccountId}:log-group:step-functions-test:*
      role: arn:aws:iam::#{AWS::AccountId}:role/step-functions-service-access
      name: aqts-ecosystem-switch-shrink-db-${self:provider.stage}
      definition:
        Comment: "AQTS Shrink Db"
        StartAt: DisableTriggerBeforeResize
        States:
          DisableTriggerBeforeResize:
            Type: Task
            InputPath: "$"
            Resource:
              Fn::GetAtt: [disableTriggerBeforeResize, Arn]
            Next: WaitForDisable
          WaitForDisable:
            Type: Wait
            Seconds: 120
            Next: ShrinkDb
          ShrinkDb:
            Type: Task
            InputPath: "$"
            Resource:
              Fn::GetAtt: [shrinkDb, Arn]
            Next: WaitForShrinkDb
          WaitForShrinkDb:
            Type: Wait
            Seconds: 1200
            Next: EnableTriggerAfterResize
          EnableTriggerAfterResize:
            Type: Task
            InputPath: "$"
            Resource:
              Fn::GetAtt: [enableTriggerAfterResize, Arn]
            End: true

    aqtsGrowDb:
      loggingConfig:
        level: ALL
        includeExecutionData: true
        destinations:
          - arn:aws:logs:${self:provider.region}:#{AWS::AccountId}:log-group:step-functions-test:*
      role: arn:aws:iam::#{AWS::AccountId}:role/step-functions-service-access
      name: aqts-ecosystem-switch-grow-db-${self:provider.stage}
      definition:
        Comment: "AQTS Grow Db"
        StartAt: DisableTriggerBeforeResize
        States:
          DisableTriggerBeforeResize:
            Type: Task
            InputPath: "$"
            Resource:
              Fn::GetAtt: [ disableTriggerBeforeResize, Arn ]
            Next: WaitForGrowDb
          WaitForDisable:
            Type: Wait
            Seconds: 120
            Next: GrowDb
          GrowDb:
            Type: Task
            InputPath: "$"
            Resource:
              Fn::GetAtt: [ growDb, Arn ]
            Next: WaitForGrowDb
          WaitForGrowDb:
            Type: Wait
            Seconds: 1200
            Next: EnableTriggerAfterResize
          EnableTriggerAfterResize:
            Type: Task
            InputPath: "$"
            Resource:
              Fn::GetAtt: [ enableTriggerAfterResize, Arn ]
            Retry:
              - ErrorEquals:
                  - States.ALL
                IntervalSeconds: 300
                MaxAttempts: 10
                BackoffRate: 1
            End: true

resources:
  Resources:
    snsTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: ${self:service}-${self:provider.stage}-topic
        TopicName: ${self:service}-${self:provider.stage}-topic
    concurrencyAlarm:
      Type: AWS::CloudWatch::Alarm
      Properties:
        AlarmName: ${self:service}-${self:provider.stage}-invocation-alarm
        AlarmDescription: Notify when the db control utilization lambda is invoked
        Namespace: 'AWS/Lambda'
        Dimensions:
          - Name: FunctionName
            Value:
              Ref: ControlDbUtilizationLambdaFunction
        MetricName: ConcurrentExecutions
        Statistic: Maximum
        ComparisonOperator: GreaterThanOrEqualToThreshold
        Threshold: 1
        Period: 60
        EvaluationPeriods: 1
        AlarmActions:
          - Ref: snsTopic
    growDbAlarm:
      Type: AWS::CloudWatch::Alarm
      Properties:
        AlarmName: ${self:service}-${self:provider.stage}-grow-db-alarm
        AlarmDescription: Notify when the cpu utilization is above 75% for five minutes
        Namespace: 'AWS/RDS'
        Dimensions:
          - Name: DBInstanceIdentifier
            Value: arn:aws:rds:us-west-2:#{AWS::AccountId}:db:nwcapture-${self:custom.environments.${self:provider.stage}}-instance1
        MetricName: CPUUtilization
        Statistic: Average
        ComparisonOperator: GreaterThanOrEqualToThreshold
        Threshold: 20
        Period: 300
        EvaluationPeriods: 1
        AlarmActions:
          - Ref: snsTopic

plugins:
  - serverless-plugin-git-variables
  - serverless-pseudo-parameters
  - serverless-python-requirements
  - serverless-step-functions
  - serverless-pseudo-parameters

package:
  exclude:
    - node_modules/**
    - Dockerfile
    - .dockerignore
    - Jenkinsfile
    - package.json
    - package-lock.json
