service: aqts-capture-ecosystem-switch

provider:
  name: aws
  region: ${opt:region, 'us-west-2'}
  stage: ${opt:stage, 'TEST'}
  runtime: python3.8
  memorySize: 128
  timeout: 30
  logRetentionInDays: 90
  deploymentBucket:
    name: ${opt:bucket, iow-cloud-applications}
  stackTags:
    "wma:applicationId": "Aquarius TS Capture Ecosystem Switch"
    "wma:contact": "Kenneth Kehl kkehl@contractor.usgs.gov"
    "wma:environment": ${self:provider.stage}
    "wma:taggingVersion": 0.0.1
    "wma:costCenter": TBD
    "wma:organization": IOW
    "displayName": "Eco-switch"
    commitIdentifier: ${git:sha1}

custom:
  # https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/ScheduledEvents.html#CronExpressions
  # The test database starts at 7 am central and stops at 6 pm central time, Monday through Friday.
  # The qa database stops at 6 pm central on Fridays
  # The production database never stops or starts according to a schedule, the lambdas exist only for manual use.
  environments:
    DEV: dev
    TEST: test
    QA: qa
    PROD: prod
  startObservationSchedules:
    TEST: cron(0 12 ? * MON-FRI *)
    QA: cron(0 12 ? * MON *)
    PROD: cron(0 12 ? * MON *)
  stopObservationSchedules:
    TEST: cron(0 23 ? * MON-FRI *)
    QA: cron(0 23 ? * FRI *)
    PROD: cron(0 23 ? * FRI *)
  startCaptureSchedules:
    TEST: cron(0 12 ? * MON-FRI *)
    QA: cron(0 12 ? * MON *)
    PROD: cron(0 12 ? * MON *)
  stopCaptureSchedules:
    TEST: cron(0 23 ? * MON-FRI *)
    QA: cron(0 23 ? * FRI *)
    PROD: cron(0 23 ? * FRI *)
  # No scheduling enabled for prod.  For qa, only Friday stops are scheduled.  For test, both stop and
  # starts are scheduled.
  startScheduleEnabled:
    TEST: true
    QA: false
    PROD: false
  stopScheduleEnabled:
    TEST: true
    QA: true
    PROD: false

  exportGitVariables: false
  vpc:
    securityGroupIds: ${ssm:/iow/retriever-capture/${self:provider.stage}/securityGroupIds~split}
    subnetIds: ${ssm:/iow/aws/vpc/${self:provider.stage}/subnetIds~split}
  observationsDb:
    connectInfo: ${ssm:/aws/reference/secretsmanager/WQP-EXTERNAL-${self:provider.stage}~true}

functions:
  StartObservationsDb:
    handler: src.handler.start_observations_db
    role: arn:aws:iam::#{AWS::AccountId}:role/csr-Lambda-Role
    environment:
      AWS_DEPLOYMENT_REGION: ${self:provider.region}
      STAGE: ${self:provider.stage}
      MAX_RETRIES: 6
    events:
      - schedule:
          rate: ${self:custom.startObservationSchedules.${self:provider.stage}}
          enabled: ${self:custom.startScheduleEnabled.${self:provider.stage}}
    vpc: ${self:custom.vpc}

  StopObservationsDb:
    handler: src.handler.stop_observations_db
    role: arn:aws:iam::#{AWS::AccountId}:role/csr-Lambda-Role
    environment:
      DB_HOST: ${self:custom.observationsDb.connectInfo.DATABASE_ADDRESS}
      DB_USER: ${self:custom.observationsDb.connectInfo.WQP_READ_ONLY_USERNAME}
      DB_NAME: ${self:custom.observationsDb.connectInfo.DATABASE_NAME}
      DB_PASSWORD: ${self:custom.observationsDb.connectInfo.WQP_READ_ONLY_PASSWORD}
      AWS_DEPLOYMENT_REGION: ${self:provider.region}
      STAGE: ${self:provider.stage}
    events:
      - schedule:
          rate: ${self:custom.stopObservationSchedules.${self:provider.stage}}
          enabled: ${self:custom.stopScheduleEnabled.${self:provider.stage}}
    vpc: ${self:custom.vpc}

  StartCaptureDb:
    handler: src.handler.start_capture_db
    role: arn:aws:iam::#{AWS::AccountId}:role/csr-Lambda-Role
    environment:
      AWS_DEPLOYMENT_REGION: ${self:provider.region}
      STAGE: ${self:provider.stage}
      MAX_RETRIES: 6
    events:
      - schedule:
          rate: ${self:custom.startCaptureSchedules.${self:provider.stage}}
          enabled: ${self:custom.startScheduleEnabled.${self:provider.stage}}
    vpc: ${self:custom.vpc}

  StopCaptureDb:
    handler: src.handler.stop_capture_db
    role: arn:aws:iam::#{AWS::AccountId}:role/csr-Lambda-Role
    environment:
      AWS_DEPLOYMENT_REGION: ${self:provider.region}
      STAGE: ${self:provider.stage}
      MAX_RETRIES: 6
    events:
      - schedule:
          rate: ${self:custom.stopCaptureSchedules.${self:provider.stage}}
          enabled: ${self:custom.stopScheduleEnabled.${self:provider.stage}}
    vpc: ${self:custom.vpc}

  ControlDbUtilization:
    handler: src.handler.control_db_utilization
    role: arn:aws:iam::#{AWS::AccountId}:role/csr-Lambda-Role
    environment:
      AWS_DEPLOYMENT_REGION: ${self:provider.region}
      LOG_LEVEL: INFO
      STAGE: ${self:provider.stage}
      MAX_RETRIES: 6
    events:
      - cloudwatchEvent:
          event:
            source:
              - 'aws.cloudwatch'
            detail:
              alarmName: ["aqts-capture-error-handler-${self:provider.stage}-error-alarm"]
    vpc: ${self:custom.vpc}


  disableTriggerBeforeShrink:
    handler: src.handler.disable_trigger_before_shrink
    role: arn:aws:iam::#{AWS::AccountId}:role/csr-Lambda-Role
    environment:
      AWS_DEPLOYMENT_REGION: ${self:provider.region}
      LOG_LEVEL: INFO
      STAGE: ${self:provider.stage}
      MAX_RETRIES: 6
    vpc: ${self:custom.vpc}


  enableTriggerAfterShrink:
    handler: src.handler.enable_trigger_after_shrink
    role: arn:aws:iam::#{AWS::AccountId}:role/csr-Lambda-Role
    environment:
      AWS_DEPLOYMENT_REGION: ${self:provider.region}
      LOG_LEVEL: INFO
      STAGE: ${self:provider.stage}
      MAX_RETRIES: 6
    vpc: ${self:custom.vpc}


  shrinkDb:
    handler: src.handler.shrink_db
    role: arn:aws:iam::#{AWS::AccountId}:role/csr-Lambda-Role
    environment:
      AWS_DEPLOYMENT_REGION: ${self:provider.region}
      LOG_LEVEL: INFO
      STAGE: ${self:provider.stage}
      MAX_RETRIES: 1
#      events:
#        - schedule:
#            rate: rate(10 minutes)
#    events:
#      - cloudwatchEvent:
#          event:
#            source:
#              - 'aws.cloudwatch'
#            detail:
#              alarmName: [ "aqts-capture-ecosystem-switch-${self:provider.stage}-shrink-db-alarm" ]
    vpc: ${self:custom.vpc}

  growDb:
    handler: src.handler.grow_db
    role: arn:aws:iam::#{AWS::AccountId}:role/csr-Lambda-Role
    environment:
      AWS_DEPLOYMENT_REGION: ${self:provider.region}
      LOG_LEVEL: INFO
      STAGE: ${self:provider.stage}
      MAX_RETRIES: 1
#    events:
#      - schedule:
#          rate: rate(10 minutes)
#    events:
#      - cloudwatchEvent:
#          event:
#            source:
#              - 'aws.cloudwatch'
#            detail:
#              alarmName: [ "aqts-capture-ecosystem-switch-${self:provider.stage}-grow-db-alarm" ]
    vpc: ${self:custom.vpc}


stepFunctions:
  stateMachines:
    aqtsShrinkDb:
      loggingConfig:
        level: ALL
        includeExecutionData: true
        destinations:
          - arn:aws:logs:${self:provider.region}:#{AWS::AccountId}:log-group:step-functions-test:*
      role: arn:aws:iam::#{AWS::AccountId}:role/step-functions-service-access
      name: aqts-ecosystem-switch-shrink-db-${self:provider.stage}
      definition:
        Comment: "AQTS Shrink Db"
        StartAt: DisableTriggerBeforeShrink
        States:
          DisableTrigger:
            Type: Task
            Resource:
              Fn::GetAtt: [disableTriggerBeforeShrink, Arn]
            Next: ShrinkDb
          ShrinkDb:
            Type: Task
            Resource:
              Fn::GetAtt: [shrinkDb, Arn]
            Next: EnableTriggerAfterShrink
          EnableTriggerAfterShrink:
            Type: Task
            Resource:
              Fn::GetAtt: [enableTriggerAfterShrink, Arn]
            Retry:
              - ErrorEquals:
                  - States.ALL
                IntervalSeconds: 600
                MaxAttempts: 10
                BackoffRate: 1
            End: true
    aqtsGrowDb:
      loggingConfig:
        level: ALL
        includeExecutionData: true
        destinations:
          - arn:aws:logs:${self:provider.region}:#{AWS::AccountId}:log-group:step-functions-test:*
      role: arn:aws:iam::#{AWS::AccountId}:role/step-functions-service-access
      name: aqts-ecosystem-switch-grow-db-${self:provider.stage}
      definition:
        Comment: "AQTS Grow Db"
        StartAt: DisableTriggerBeforeGrow
        States:
          DisableTrigger:
            Type: Task
            Resource:
              Fn::GetAtt: [ disableTriggerBeforeGrow, Arn ]
            Next: GrowDb
          GrowDb:
            Type: Task
            Resource:
              Fn::GetAtt: [ growDb, Arn ]
            Next: enableTriggerAfterGrow
          EnableTriggerAfterShrink:
            Type: Task
            Resource:
              Fn::GetAtt: [ enableTriggerAfterGrow, Arn ]
            Retry:
              - ErrorEquals:
                  - States.ALL
                IntervalSeconds: 600
                MaxAttempts: 10
                BackoffRate: 1
            End: true



resources:
  Resources:
    snsTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: ${self:service}-${self:provider.stage}-topic
        TopicName: ${self:service}-${self:provider.stage}-topic
    concurrencyAlarm:
      Type: AWS::CloudWatch::Alarm
      Properties:
        AlarmName: ${self:service}-${self:provider.stage}-invocation-alarm
        AlarmDescription: Notify when the db control utilization lambda is invoked
        Namespace: 'AWS/Lambda'
        Dimensions:
          - Name: FunctionName
            Value:
              Ref: ControlDbUtilizationLambdaFunction
        MetricName: ConcurrentExecutions
        Statistic: Maximum
        ComparisonOperator: GreaterThanOrEqualToThreshold
        Threshold: 1
        Period: 60
        EvaluationPeriods: 1
        AlarmActions:
          - Ref: snsTopic
    growDbAlarm:
      Type: AWS::CloudWatch::Alarm
      Properties:
        AlarmName: ${self:service}-${self:provider.stage}-grow-db-alarm
        AlarmDescription: Notify when the cpu utilization is above 75% for an hour
        Namespace: 'AWS/RDS'
        Dimensions:
          - Name: DBInstanceIdentifier
            Value: arn:aws:rds:us-west-2:#{AWS::AccountId}:db:nwcapture-${self:custom.environments.${self:provider.stage}}-instance1
        MetricName: CPUUtilization
        Statistic: Average
        ComparisonOperator: GreaterThanOrEqualToThreshold
        Threshold: 75
        Period: 300
        EvaluationPeriods: 1
        AlarmActions:
          - Ref: snsTopic
    shrinkDbAlarm:
      Type: AWS::CloudWatch::Alarm
      Properties:
        AlarmName: ${self:service}-${self:provider.stage}-shrink-db-alarm
        AlarmDescription: Notify when the cpu utilization is below 50% for an hour
        Namespace: 'AWS/RDS'
        Dimensions:
          - Name: DBInstanceIdentifier
            Value: arn:aws:rds:us-west-2:#{AWS::AccountId}:db:nwcapture-${self:custom.environments.${self:provider.stage}}-instance1
        MetricName: CPUUtilization
        Statistic: Average
        ComparisonOperator: LessThanOrEqualToThreshold
        Threshold: 25
        Period: 1800
        EvaluationPeriods: 1
        # TODO should be breaching?  Should be ignore?
        TreatMissingData: missing
        AlarmActions:
          - Ref: snsTopic


plugins:
  - serverless-plugin-git-variables
  - serverless-pseudo-parameters
  - serverless-python-requirements

package:
  exclude:
    - node_modules/**
    - Dockerfile
    - .dockerignore
    - Jenkinsfile
    - package.json
    - package-lock.json
